import { useEffect } from 'react'
import { useSelector } from 'react-redux'
import { useRouter } from 'next/router'
import Head from 'next/head'

export default function Layout({ children }) {
    const router = useRouter()
    const { user } = useSelector(({ auth }) => auth)

    useEffect(() => {
        if (user) {
            router.push('/buyer/dashboard')
        }
    }, [user])

    return (
        <>
            <Head>
                <title>Auth</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {children}
            </main>
        </>
    )
}