import { useState, createContext, useContext } from 'react'
import Head from 'next/head'

const CurrentUserContext = createContext(null)

export default function Layout({ children }) {
    const [currentUser, setCurrentUser] = useState('test')

    return (
        <>
            <Head>
                <title>Context</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <CurrentUserContext.Provider
                    value={currentUser}
                >
                    {children}
                </CurrentUserContext.Provider>
            </main>
        </>
    )
}

export { CurrentUserContext }